FROM debian:buster

RUN apt update
RUN apt dist-upgrade -y
RUN apt-get install -y libmariadb3 libssl1.0 libreadline5 zlib1g \
        libncurses5 libbz2-1.0 wget libace-6.4.5 \
        mariadb-client libboost-system1.67.0 libboost-filesystem1.67.0 \
        libboost-thread1.67.0 libboost-program-options1.67.0 \
        libboost-iostreams1.67.0 gdb

ADD bin/worldserver /tc/bin/worldserver
ADD bin/worldserver.dbg /tc/bin/worldserver.dbg

WORKDIR /tc/bin

EXPOSE 8085 7878
VOLUME ["/tc/core"]
CMD ["gdb", "--symbols=/tc/bin/worldserver.dbg", "--core=/tc/core/core.worldserver", "--exec=/tc/bin/worldserver"]
