FROM debian:buster

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt update
RUN apt dist-upgrade -y
RUN apt-get install -y libmariadb3 libssl1.0 libreadline5 zlib1g \
        libncurses5 libbz2-1.0 wget libace-6.4.5 \
        mariadb-client libboost-system1.67.0 libboost-filesystem1.67.0 \
        libboost-thread1.67.0 libboost-program-options1.67.0 \
        libboost-iostreams1.67.0 gdb


RUN pip3 install flask gunicorn

RUN mkdir -p /tc/logs
RUN mkdir -p /tc/data
RUN mkdir -p /tc/bin

ADD bin/worldserver /tc/bin
ADD scripts/misc/world_metrics.py /tc/bin
ADD image/supervisord.conf /tc/supervisord.conf

WORKDIR /tc/bin

EXPOSE 8080 8085 7878
VOLUME ["/tc/logs", "/tc/data", "/tc/etc"]
CMD ["supervisord", "-c", "/tc/supervisord.conf", "-n"]
