FROM debian:jessie

RUN apt-get install -y libmysqlclient18 libssl1.0.0 libreadline5 libace-6.2.8 \
    zlib1g libncurses5 libbz2-1.0 libpthread-workqueue0

RUN mkdir -p /tc/logs /tc/etc /tc/bin /var/core

ADD binaries/bin/authserver /tc/bin/authserver

WORKDIR /tc
CMD ["/tc/bin/authserver"]

EXPOSE 3724
